version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=tpachat
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - /var/lib/mysql

  spring_app:
    image: lindakheder/tpachatproject
    container_name: achatspring
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3308/tpachat?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
